name: Build macOS DMG

on:
    workflow_dispatch:

jobs:
    build-mac:
        runs-on: macos-13

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies & Build
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller
                  pyinstaller --onefile --windowed v2.py \
                    --hidden-import=cv2 \
                    --hidden-import=numpy \
                    --collect-all customtkinter
                    --add-data "configs:configs"

            - name: Check dist contents
              run: |
                  ls -lh dist
                  du -sh dist/*

            - name: Create DMG
              run: |
                  hdiutil create \
                      -volname "v2" \
                      -srcfolder dist \
                      -ov \
                      -format UDZO \
                      v2.dmg
                  ls -lh v2.dmg

            - name: Upload DMG artifact
              uses: actions/upload-artifact@v4
              with:
                  name: macOS-DMG
                  path: v2.dmg